name: Run Unit Tests

on: [push, pull_request]  # Runs tests on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pandas openpyxl nltk
          python -c "import nltk; nltk.download('stopwords')"

      - name: Run Tests
        run: pytest tests/test_similarity.py
