# This is a basic workflow to help you get started with Actions

name: TestFlow

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pandas openpyxl nltk
          python -c "import nltk; nltk.download('stopwords')"

      - name: Run Tests
        run: pytest tests/test_similarity.py
